// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDA8oKg4nQEgCR6Wql5pUqjkbT4nJrXo',
    appId: '1:611666021219:web:c66b4826a8064983906156',
    messagingSenderId: '611666021219',
    projectId: 'yapilacaklar-listesi-2b907',
    authDomain: 'yapilacaklar-listesi-2b907.firebaseapp.com',
    storageBucket: 'yapilacaklar-listesi-2b907.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLw80qfeRvFIdrTPvBV8BzZRAjhCK6rss',
    appId: '1:611666021219:android:42625bda63bd63f6906156',
    messagingSenderId: '611666021219',
    projectId: 'yapilacaklar-listesi-2b907',
    storageBucket: 'yapilacaklar-listesi-2b907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1c3ywjY7bvQ4edlW2eVmj9_Ob_DTgo9s',
    appId: '1:611666021219:ios:039fd83d217ff49e906156',
    messagingSenderId: '611666021219',
    projectId: 'yapilacaklar-listesi-2b907',
    storageBucket: 'yapilacaklar-listesi-2b907.appspot.com',
    iosBundleId: 'com.example.yapilacaklarlistesi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1c3ywjY7bvQ4edlW2eVmj9_Ob_DTgo9s',
    appId: '1:611666021219:ios:039fd83d217ff49e906156',
    messagingSenderId: '611666021219',
    projectId: 'yapilacaklar-listesi-2b907',
    storageBucket: 'yapilacaklar-listesi-2b907.appspot.com',
    iosBundleId: 'com.example.yapilacaklarlistesi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcDA8oKg4nQEgCR6Wql5pUqjkbT4nJrXo',
    appId: '1:611666021219:web:9d4cdb895b1ad222906156',
    messagingSenderId: '611666021219',
    projectId: 'yapilacaklar-listesi-2b907',
    authDomain: 'yapilacaklar-listesi-2b907.firebaseapp.com',
    storageBucket: 'yapilacaklar-listesi-2b907.appspot.com',
  );

}